language: ruby

services:
  - docker

before_install:
- docker pull sagebionetworks/nrgrsynapseglue

script: 
- >
  docker run --rm -it 
  -e USERNAME=${USERNAME}
  -e PASSWORD=${PASSWORD}
  -e CONFIGURATION_TABLE_ID=${CONFIGURATION_TABLE_ID}
  -e ORIGINAL_APPLICATION_TEAM_ID=${ORIGINAL_APPLICATION_TEAM_ID}
  -e CC_RECIPIENT=${CC_RECIPIENT}
  -e HMAC_SECRET_KEY=${HMAC_SECRET_KEY}
  -e TABLE_ID=${TABLE_ID}
  -e EVALUATION_ID=${EVALUATION_ID}
  -e GMAIL_ADDRESS=${GMAIL_ADDRESS}
  -e GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
  -e GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
  -e GOOGLE_OAUTH_REFRESH_TOKEN=${GOOGLE_OAUTH_REFRESH_TOKEN}
  -e MAIL_IN_FOLDER=${MAIL_IN_FOLDER}
  -e MAIL_OUT_FOLDER=${MAIL_OUT_FOLDER}
  -e MESSAGE_CONTAINER_ENTITY_ID=${MESSAGE_CONTAINER_ENTITY_ID}
  sagebionetworks/nrgrsynapseglue
