
name: Cron job for sending token emails and processing received tokens

on:  
  schedule:
    - cron: '*/15 * * * *'

jobs:
  cron:
    name: cron
    runs-on: ubuntu-latest

    steps:
    - name: checkout source code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: build with Maven
      run: mvn clean install
    - name: run
      run: mvn --file pom.xml exec:java
      env:
        SYNAPSE_ACCESS_TOKEN: ${{ secrets.SYNAPSE_ACCESS_TOKEN }}
        CONFIGURATION_TABLE_ID: syn5763221
        ORIGINAL_APPLICATION_TEAM_ID: 3324934
        CC_RECIPIENT: 3375085
        HMAC_SECRET_KEY: ${{ secrets.HMAC_SECRET_KEY }}
        TABLE_ID: syn3243669
        EVALUATION_ID: 3249209
        GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
        GOOGLE_OAUTH_CLIENT_ID: 752321674974.apps.googleusercontent.com
        GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
        GOOGLE_OAUTH_REFRESH_TOKEN: ${{ secrets.GOOGLE_OAUTH_REFRESH_TOKEN }}
        MAIL_IN_FOLDER: CMC-IN
        MAIL_OUT_FOLDER: CMC-OUT
        MESSAGE_CONTAINER_ENTITY_ID: syn3278591
